export const AboutInfoContent = [
  `%title # Welcome!%`,
  ``,
  `Hi! I’m Miquel (or Mike), a software engineer based in %link [Girona](https://en.wikipedia.org/wiki/Girona)%`,
  `I’m a software engineer who mainly works with frontend frameworks, mainly with`,
  `React and Svelte. I’m also really interested in working with other technologies`,
  `and I often take the opportunity to challenge myself with Rust (for the Advent`,
  `of Code, mainly!).`,
  ``,
  `I’m always open for ideas, staying up to date with the technologies I use and also`,
  `learning and trying whatever I find interesting. While I have quite some projects`,
  `in my GitHub profile, most of them are simply a way for me to challenge myself and`,
  `try new things or approaches.`,
  `In a way, this portfolio is also a challenge/idea that came to my mind, most likely`,
  `while training on the bike.`,
  ``,
  `When I’m not in my desktop, I’m most likely on the road, training and enjoying`,
  `%comment TODO: Update the following line once it’s outdated! --&gt;%`,
  `cycling with my friends. This year (2025) I have started training to compete in the`,
  `national time trial championships!`,
  `Cycling and sport in general have been a gateway from my desk and it’s been`,
  `countless times that I have solved a problem or came up with an idea `,
  `*while training*!`,
  ``,
  `I also appreciate spending time in nature, with my partner and reading (avid`,
  `fantasy reader 🐉!)`,
  ``,
  `Last, I use neovim btw B)`,
  ``,
  `%title ## Links and others!%`,
  ``,
  `%class [text-yellow](&nbsp;&bull; %link [Strava profile](https://www.strava.com/athletes/40516812)%)%`,
  `%class [text-yellow](&nbsp;&bull; %link [Github profile](https://github.com/mikededo)%)%`,
  `&nbsp;&bull; Open my projects with %class [text-peach](\`CMD + p\`)%`
];
